# Generated by Django 2.2.7 on 2020-04-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('rank', models.IntegerField()),
                ('no_matches', models.IntegerField()),
                ('address', models.CharField(max_length=10)),
            ],
        ),
    ]
